global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quantum_service'
    static_configs:
      - targets: ['quantum_service:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'neural_service'
    static_configs:
      - targets: ['neural_service:5001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'blockchain_service'
    static_configs:
      - targets: ['blockchain_service:5002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'financial_service'
    static_configs:
      - targets: ['financial_service:5003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'optimization_service'
    static_configs:
      - targets: ['optimization_service:5004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
